

fun main() {
    var Strlist:MutableList<String> = mutableListOf()
    println("MutableList")
    println(Strlist)
    Strlist.add(0,"ok")
    println(Strlist)
    Strlist.add(0,"ko")
    println(Strlist)
    Strlist.add(0,"abc")
    println(Strlist)
    Strlist.add(0,"rho")
    println(Strlist)
    Strlist.add(0,"ro")
    println(Strlist)
    Strlist.add(0,"quo")
    println(Strlist)
    Strlist.add(0,"sh")
    println(Strlist)
    Strlist.add(0,"sdrg")
    println(Strlist)
    Strlist.add(0,"sdgh")
    println(Strlist)
    Strlist.add(0,"rj")
    println(Strlist)
    Strlist.add(0,"rj")
    println(Strlist)
    Strlist.add(0,"rj")
    println(Strlist)
    Strlist.sort()
    println(Strlist)

    println("LinkedHashSet")
    var strhs :LinkedHashSet<String> = linkedSetOf()
    println(strhs)
    strhs.add("ok")
    println(strhs)
    strhs.add("sv")
    println(strhs)
    strhs.add("sdv")
    println(strhs)
    strhs.add("nf")
    println(strhs)
    strhs.add("zre")
    println(strhs)
    strhs.add("cv")
    println(strhs)
    strhs.add("kh")
    println(strhs)
    strhs.add("kh")
    println(strhs)
    strhs.add("kh")
    println(strhs)


    println("HashSet")
    var strh :HashSet<String> = hashSetOf()
    println(strh)
    strh.addAll(strhs)
    println(strh)
}

